config/routes.rb
Rails.application.routes.draw do
  resources :scores
  root 'scores#index'
  get 'admin', controller: "scores", action: "admin"
end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id          :integer          not null, primary key
#  team        :string
#  blairScore  :integer
#  peddieScore :integer
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Score < ActiveRecord::Base

  # Score validations
  validates :blairScore, presence: true
  validates :peddieScore, presence: true
  validates :team, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all.order("team ASC")
    @blair = 0
    @peddie = 0
    @tie = 0
    @scores.each do |score|
      if (score.blairScore > score.peddieScore)
        @blair = @blair+1
      elsif (score.peddieScore > score.blairScore)
        @peddie = @peddie+1
      else
        @tie = @tie+1
      end
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  def admin
    @scores = Score.all.order("team ASC")
    @score = Score.new
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Success' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Success' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:team, :blairScore, :peddieScore, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Peddie Day
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    = yield

app/views/scores/_form.html.haml
%br
= form_for @score do |f|
  .text-center=@score.team
  %table.table.table-bordered
    %tr
      %th.text-center
        Blair
      %th.text-center
        Peddie
    %tr
      %td
        = f.number_field :blairScore, class: "form-score"
      %td
        = f.number_field :peddieScore, class: "form-score"
  %br
  .form-group
    = f.check_box :active
    Game is still active
  %br
  .actions
    = f.submit 'Save Score', class: "btn btn-success btn-block"

app/views/scores/admin.html.haml
.header-bar
  %h1.text-center Scoremaster

%table.table
  - @scores.each do |score|
    %tr
      %td
        = link_to score.team, edit_score_path(score)

app/views/scores/edit.html.haml
.header-bar
  %h1.text-center Edit Score

%p.text-success#notice= notice

= render 'form'

%br
= link_to 'Back', {controller: :scores, action: :admin}, class: "btn btn-lg btn-primary btn-block"

app/views/scores/index.html.haml
.header-bar
  %h1.text-center Peddie Day

%input{:onclick => "history.go(0)", :type => "button", :value => "Refresh ↺", class: "btn btn-lg btn-block btn-success"}/

%table.table.table-bordered
  %thead
    %tr
      %th.text-center.blair.col-xs-4 B
      %th.text-center.tie.col-xs-4 Tie
      %th.text-center.peddie.col-xs-4 P

  %tbody
    %tr
      %td.text-center= @blair
      %td.text-center= @tie
      %td.text-center= @peddie

%table.table.table-bordered
  %thead
    %tr
      %th Team
      %th.text-center.blair B
      %th.text-center.peddie P

  %tbody
    - @scores.each do |score|
      %tr
        %td
          - if score.active == false
            %span.text-muted= score.team
            %em.small.text-muted.text-right Ended
          - else
            = score.team
        - if score.blairScore > score.peddieScore
          %td.text-center.blair= score.blairScore
          %td.text-center.tie= score.peddieScore
        - elsif score.peddieScore > score.blairScore
          %td.text-center.tie= score.blairScore
          %td.text-center.peddie= score.peddieScore
        - else
          %td.text-center.tie= score.blairScore
          %td.text-center.tie= score.peddieScore

app/views/scores/new.html.haml
%h1 New score

= render 'form'

= link_to 'Back', scores_path

app/views/scores/show.html.haml
.header-bar
  %h1.text-center Result
%p.text-success#notice= notice

%p
  %b Team:
  = @score.team
%p
  %b Blair:
  = @score.blairScore
%p
  %b Peddie:
  = @score.peddieScore
%p
  %b Game is still active:
  - if @score.active == true
    Yes
  - else
    No

%br
= link_to 'Edit', edit_score_path(@score), class: "btn btn-lg btn-default btn-block"
%br
= link_to 'Back', {controller: :scores, action: :admin}, class: "btn btn-lg btn-primary btn-block"